[2024-10-19T15:01:01.609+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: ambev_data_quality_pipeline.run_data_quality manual__2024-10-19T15:00:59.635949+00:00 [queued]>
[2024-10-19T15:01:01.616+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: ambev_data_quality_pipeline.run_data_quality manual__2024-10-19T15:00:59.635949+00:00 [queued]>
[2024-10-19T15:01:01.616+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-10-19T15:01:01.616+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-10-19T15:01:01.617+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-10-19T15:01:01.625+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): run_data_quality> on 2024-10-19 15:00:59.635949+00:00
[2024-10-19T15:01:01.628+0000] {standard_task_runner.py:55} INFO - Started process 26930 to run task
[2024-10-19T15:01:01.630+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ambev_data_quality_pipeline', 'run_data_quality', 'manual__2024-10-19T15:00:59.635949+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/dag_dataquality.py', '--cfg-path', '/tmp/tmpgs1xq_ox']
[2024-10-19T15:01:01.632+0000] {standard_task_runner.py:83} INFO - Job 42: Subtask run_data_quality
[2024-10-19T15:01:01.642+0000] {logging_mixin.py:137} WARNING - /usr/local/lib/python3.9/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-19T15:01:01.678+0000] {task_command.py:388} INFO - Running <TaskInstance: ambev_data_quality_pipeline.run_data_quality manual__2024-10-19T15:00:59.635949+00:00 [running]> on host 39b0b1bd9d5a
[2024-10-19T15:01:01.721+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Klaus_Rezende
AIRFLOW_CTX_DAG_ID=ambev_data_quality_pipeline
AIRFLOW_CTX_TASK_ID=run_data_quality
AIRFLOW_CTX_EXECUTION_DATE=2024-10-19T15:00:59.635949+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-19T15:00:59.635949+00:00
[2024-10-19T15:01:01.721+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-10-19T15:01:01.722+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/scripts/data_quality_brewery.py']
[2024-10-19T15:01:01.728+0000] {subprocess.py:86} INFO - Output:
[2024-10-19T15:01:05.094+0000] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2024-10-19T15:01:05.095+0000] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2024-10-19T15:01:05.276+0000] {subprocess.py:93} INFO - 24/10/19 15:01:05 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-10-19T15:01:09.231+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-10-19T15:01:09.231+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/data_quality_brewery.py", line 47, in <module>
[2024-10-19T15:01:09.232+0000] {subprocess.py:93} INFO -     total_validations = len(results['results'])
[2024-10-19T15:01:09.232+0000] {subprocess.py:93} INFO - NameError: name 'results' is not defined
[2024-10-19T15:01:09.982+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-10-19T15:01:09.993+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-19T15:01:09.996+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=ambev_data_quality_pipeline, task_id=run_data_quality, execution_date=20241019T150059, start_date=20241019T150101, end_date=20241019T150109
[2024-10-19T15:01:10.006+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 42 for task run_data_quality (Bash command failed. The command returned a non-zero exit code 1.; 26930)
[2024-10-19T15:01:10.019+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-10-19T15:01:10.035+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
